### ISSUE TITLE
something broken in videojs 4.12

### ISSUE THREAD

**Issue by dtrikannad** [rsadwick/videojs-disable-progress#3]
Hey Ryan,

Great plugin! It appears to be broken in 4.12 of videojs. Is this something you can resolve? Hopefully, it is a quick fix.

Thanks.

Deep

**Comment by rsadwick** [comment]
In 4.12, the plugin doesn't function as expected.  It does work in 4.11 though.  I'll take a look later this week - until then I'd recommend using 4.11.

**Comment by rsadwick** [comment]
Took another glance - I may need to rework it within the new plugin framework for videojs.  It's not a big deal since I have another plugin I'm cookin up within the same framework.  I'll try to get it fixed before the new week :)

**Comment by sgavali** [comment]
I'm using this for a case where I need to change video source, I see plugin is working with dev version of videojs but not with release, I'm using version 4.12.7. Could it be issue with minifying of js ?

**Comment by rsadwick** [comment]
Yes, it would be an issue with the release version that is minified.  I'll take a look - it seems like a lot of video.js plugins run into this same issue.

**Comment by LRancez** [comment]
Hi there, this plugin is not working on videojs because, at some point, this changed in videojs:
https://github.com/rsadwick/videojs-disable-progress/blob/master/src/videojs.disableProgress.js#L53

it should use
player.controlBar.progressControl.seekBar.handleMouseDown
player.controlBar.progressControl.seekBar.handleMouseDown
player.controlBar.progressControl.seekBar.handleClick

**Comment by rsadwick** [comment]
Feel free to make a PR, haven't had time to update yet but will soon
